apiVersion: kustomize.config.k8s.io/v1beta1
commonLabels:
  app: test-july-13
configMapGenerator:
- envs:
  - .env
  name: test-july-13-configmap
generatorOptions:
  disableNameSuffixHash: true
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- ingress.yaml
